# Generated by Django 4.2.4 on 2023-09-01 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
